### ISSUE TITLE
installation of cmake modules

### ISSUE THREAD

**Issue by fkanehiro** [arntanguy/mesh_sampling#3]
cmake modules are always installed in /usr/local/lib/cmake/mesh_sampling.
https://github.com/arntanguy/mesh_sampling/blob/master/CMakeLists.txt#L32-L43

Is this necessary? How about installing them to $CMAKE_INSTALL_PREFIX/lib/cmake/mesh_sampling?

**Comment by arntanguy** [comment]
That's indeed a mistake, should be fixed in 6efcb49.

**Comment by fkanehiro** [comment]
Thanks!
