### ISSUE TITLE
PCL version

### ISSUE THREAD

**Issue by fkanehiro** [arntanguy/mesh_sampling#4]
This package cannot be compiled on ubuntu16.04. Because ubuntu16.04 provides PCL1.7 whereas this package requires PCL1.8.
https://github.com/arntanguy/mesh_sampling/blob/master/CMakeModules/Findmesh_sampling_3rd_party_PCL.cmake
Is PCL1.8 really necessary? 
I could at least compile and run with PCL1.7.

**Comment by arntanguy** [comment]
From a code perspective it should work as it doesn't use anything fancy from the PCL library (just the pointcloud data structure and the exporting features).

I'll set it up in CI to test ;)

**Comment by arntanguy** [comment]
Handled by #5
